name: Fast Synapse Deploy
description: Deploy Azure Synapse artifacts quickly!
author: Shawn McGough
inputs:
  args:
    description: 'Arguments'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Deploy from Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/SynapseDeploy
        ${{ github.action_path }}/SynapseDeploy ${{ inputs.args }}
    - name: Deploy from Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        ${{ github.action_path }}\SynapseDeploy.exe ${{ inputs.args }}